variables:
  AWS_ACCESS_KEY_ID=223344
  AWS_SECRET_ACCESS_KEY=dummy
  ENDPOINT_URL="http://localhost:8000"
  REGION="eu-west-1"
  REGISTRY="https://docker.registry.com/somepath"
  TABLE_NAME="devops_challange"
  CODE_NAME="codeDoctor"
build:
  script:
    - docker-compose up --build -d
    - sleep 5